# coding: utf-8

$keyboard_mapping = {
  '1'   => :volume0,
  '2'   => :volume20,
  '3'   => :volume30,
  '4'   => :volume40,
  '5'   => :volume50,
  '6'   => :volume60,
  '7'   => :volume70,
  '8'   => :volume80,
  '9'   => :volume90,
  '0'   => :volume100,
  'ß'   => :ignore,
  '´'   => :ignore,

  'q'   => :stop,
  'w'   => :deutschlandfunk,
  'e'   => :deutschlandradio_kultur,
  'r'   => :dradio_wissen,
  't'   => :ignore,
  'z'   => :ignore,
  'u'   => :ignore,
  'i'   => :ignore,
  'o'   => :ignore,
  'p'   => :ignore,
  'ü'   => :ignore,
  '+'   => :ignore,

  'a'   => :tagesschau,
  's'   => :tagesschau_latest_news_show,
  'd'   => :ignore,
  'f'   => :ignore,
  'g'   => :ignore,
  'h'   => :ignore,
  'j'   => :ignore,
  'k'   => :ignore,
  'l'   => :ignore,
  'ö'   => :ignore,
  'ä'   => :ignore,
  '#'   => :ignore,

  'y'   => :marvel_epic_soundtrack,
  'x'   => :epic_soundtrack_1,
  'c'   => :secret_of_mana_soundtrack,
  'v'   => :ghibli_soundtrack,
  'b'   => :amelie_soundtrack,
  'n'   => :classic_mix,
  'm'   => :dark_minimal_techo_mix,
  ','   => :ignore,
  '.'   => :ignore,

  # Numpad
  '/'   => :custom_1,
  '*'   => :custom_2,
  '-'   => :custom_3,

  # F keys
  'F1'  => :ignore,
  'F2'  => :ignore,
  'F3'  => :ignore,
  'F4'  => :ignore,
  'F5'  => :ignore,
  'F6'  => :ignore,
  'F7'  => :ignore,
  'F8'  => :ignore,
  'F9'  => :ignore,
  'F10' => :status,
  'F11' => :hot_reload,
  'F12' => :quit,
}
